HW3 is completed
april1858/ohw pull request #4
Opened 2024-02-16 06:34 UTC by april1858

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-02-16 17:43 UTC, hungry-honeybadger requested changes
Хорошее начало, но в коде есть потенциальная  паника и ошибка в имени модуля в файле go.mod

2024-02-16 17:43 UTC, hungry-honeybadger commented on hw03_frequency_analysis/top.go
> +	fr10 := allFr[:10]
если `allFr` вернет слайс где  нет 10  элементов, то будет паника

2024-02-17 08:08 UTC, vladislavmass approved these changes
Хорошая работа, но код пере усложнен

2024-02-17 08:08 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	sort.Slice(countsSort, func(i, j int) bool {
А что мешало тут сделать сразу 2 сортировки?

2024-02-17 08:08 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +func frAnalysis10(cs []Frequency) []Frequency {
Имя  этой функции  не отображает ее назначение

2024-02-17 08:08 UTC, vladislavmass commented on hw03_frequency_analysis/top.go
> +	allFr := frAnalysis10(countsSort)
Имя  этой переменной  не отображает ее назначение

2024-02-28 02:43 UTC, april1858 commented
!

2024-02-28 02:55 UTC, merged